apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cms-web
spec:
  serviceName: cms-web
  replicas: 1
  selector:
    matchLabels:
      app: cms-web
  template:
    metadata:
      labels:
        app: cms-web
    spec:
      containers:
        - name: mysql
          image: ghcr.io/xibosignage/xibo-cms:release-4.1.2
          env:
            - name: MYSQL_HOST
              value: cms-db
            - name: CMS_USE_MEMCACHED
              value: false
            - name: MYSQL_PASSWORD
              value: {{ .Values.cmsDb.password }}
            - name: CMS_SERVER_NAME
              value: {{ .Values.ingressHost }}
          volumeMounts:
            - name: cms-data
              mountPath: /var/www
  volumeClaimTemplates:
    - metadata:
        name: cms-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cms-db
spec:
  serviceName: cms-db
  replicas: 1
  selector:
    matchLabels:
      app: cms-db
  template:
    metadata:
      labels:
        app: cms-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env: 
            - name: MYSQL_DATABASE
              value: cms
            - name: MYSQL_USER
              value: cms
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_PASSWORD
              value: {{ .Values.cmsDb.password }}
            - name: CMS_SERVER_NAME
              value: {{ .Values.ingressHost }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn