apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cms-web
spec:
  serviceName: cms-web
  replicas: 1
  selector:
    matchLabels:
      app: cms-web
  template:
    metadata:
      labels:
        app: cms-web
    spec:
      containers:
        - name: mysql
          image: ghcr.io/xibosignage/xibo-cms:release-4.1.2
          envFrom:
            - configMapRef:
                name: cms-config
          volumeMounts:
            - name: cms-data
              mountPath: /var/www
  volumeClaimTemplates:
    - metadata:
        name: cms-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cms-db
spec:
  serviceName: cms-db
  replicas: 1
  selector:
    matchLabels:
      app: cms-db
  template:
    metadata:
      labels:
        app: cms-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: cms-config
          volumeMounts:
            - name: cms-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn