apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cms-ingress
spec:
  tls:
    - hosts:
        - {{ .Values.ingressHost }}
      secretName: cert
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cms-web
                port:
                  number: 80
