apiVersion: v1
kind: Service
metadata:
  name: cms-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cms-web
---
apiVersion: v1
kind: Service
metadata:
  name: cms-db
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: cms-db
---
apiVersion: v1
kind: Service
metadata:
  name: cms-xmr
spec:
  type: LoadBalancer
  ports:
    - port: 9505
      targetPort: 9505
  selector:
    app: cms-xmr

